import {
  IconBasket,
  IconBitcoin,
  IconBook,
  IconCar,
  IconCarDashboard,
  IconCart,
  IconCigarette,
  IconCoffee,
  IconCut,
  IconDanger,
  IconDollar,
  IconDrink,
  IconEdit,
  IconEyeShow,
  IconFitness,
  IconGameController,
  IconGift,
  IconHiking,
  IconHome,
  IconLaptop,
  IconLightbulb,
  IconLove,
  IconPainter,
  IconPaw,
  IconPill,
  IconPizza,
  IconSalary,
  IconShield,
  IconTools,
  IconTshirt,
  IconWallet,
  IconWeight,
} from "./icons";

export const categoryIcons = [
  { id: 1, iconJSX: <IconPizza /> }, // FOOD
  { id: 2, iconJSX: <IconCar /> }, // TRANSPORT
  { id: 3, iconJSX: <IconDrink /> }, // ENTERTAINMENT
  { id: 4, iconJSX: <IconSalary /> }, // SALARY
  { id: 5, iconJSX: <IconLaptop /> }, // FREELANCE
  { id: 6, iconJSX: <IconLightbulb /> }, // OTHER
  { id: 7, iconJSX: <IconCarDashboard /> },
  { id: 8, iconJSX: <IconPainter /> },
  { id: 9, iconJSX: <IconGift /> },
  { id: 10, iconJSX: <IconHome /> },
  { id: 11, iconJSX: <IconLove /> },
  { id: 12, iconJSX: <IconCoffee /> },
  { id: 13, iconJSX: <IconBitcoin /> },
  { id: 14, iconJSX: <IconDanger /> },
  { id: 15, iconJSX: <IconBasket /> },
  { id: 16, iconJSX: <IconEdit /> },
  { id: 17, iconJSX: <IconEyeShow /> },
  { id: 18, iconJSX: <IconCigarette /> },
  { id: 19, iconJSX: <IconGameController /> },
  { id: 20, iconJSX: <IconTshirt /> },
  { id: 21, iconJSX: <IconCut /> },
  { id: 22, iconJSX: <IconPill /> },
  { id: 23, iconJSX: <IconShield /> },
  { id: 24, iconJSX: <IconHiking /> },
  { id: 25, iconJSX: <IconDollar /> },
  { id: 26, iconJSX: <IconWallet /> },
  { id: 27, iconJSX: <IconFitness /> },
  { id: 28, iconJSX: <IconCart /> },
  { id: 29, iconJSX: <IconTools /> },
  { id: 30, iconJSX: <IconPaw /> },
  { id: 31, iconJSX: <IconBook /> },
  { id: 32, iconJSX: <IconWeight /> },
];
